// Auto-generated by System Creators — do not edit manually
import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { Posts } from './entities/posts.entity';
import { PostsController } from './controllers/posts.controller';
import { PostsService } from './services/posts.service';
import { ActivityLogsModule } from '@/modules/activity-logs/activity-logs.module';
import { StorageModule } from '@/modules/storage/storage.module';

import { Category } from '@/modules/managements/sc_category/entities/category.entity';
import { Tag } from '@/modules/managements/sc_tag/entities/tag.entity';

@Module({
  imports: [TypeOrmModule.forFeature([Posts, Tag, Category]), ActivityLogsModule, StorageModule],
  controllers: [PostsController],
  providers: [PostsService],
  exports: [PostsService],
})
export class PostsModule {}
