"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.QueryCategoryDto = void 0;
// Auto-generated by System Creators — do not edit manually
const query_dto_1 = require("@/common/dto/query.dto");
class QueryCategoryDto extends query_dto_1.QueryDto {
    static sortableFields = ['id', 'name', 'createdAt', 'updatedAt'];
    static searchableFields = ['name'];
}
exports.QueryCategoryDto = QueryCategoryDto;
