// Auto-generated by System Creators — do not edit manually
import { IsNumber, IsOptional, IsString } from 'class-validator';

export class CreateTest2Dto {
  @IsOptional()
  @IsString()
  test1?: string;

  @IsOptional()
  @IsOptional()
  @IsNumber()
  test2?: number;
}
