"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.QueryTest2Dto = void 0;
// Auto-generated by System Creators — do not edit manually
const query_dto_1 = require("../../../../common/dto/query.dto");
class QueryTest2Dto extends query_dto_1.QueryDto {
    static sortableFields = ['id', 'createdAt', 'updatedAt'];
    static searchableFields = [];
}
exports.QueryTest2Dto = QueryTest2Dto;
