// Auto-generated by System Creators — do not edit manually
import { QueryDto } from '@/common/dto/query.dto';

export class QueryTest2Dto extends QueryDto {
  static readonly sortableFields: string[] = ['id', 'createdAt', 'updatedAt'];
  static readonly searchableFields: string[] = [];
}
