"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpdateTest2Dto = void 0;
// Auto-generated by System Creators — do not edit manually
const mapped_types_1 = require("@nestjs/mapped-types");
const create_test2_dto_1 = require("./create-test2.dto");
class UpdateTest2Dto extends (0, mapped_types_1.PartialType)(create_test2_dto_1.CreateTest2Dto) {
}
exports.UpdateTest2Dto = UpdateTest2Dto;
