// Auto-generated by System Creators — do not edit manually
import { Injectable, ConflictException, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository, In } from 'typeorm';
import { Product } from '../entities/product.entity';
import { CreateProductDto } from '../dto/create-product.dto';
import { UpdateProductDto } from '../dto/update-product.dto';
import { QueryProductDto } from '../dto/query-product.dto';
import { ActivityLogsService } from '@/modules/activity-logs/services/activity-logs.service';

import { Tag } from '@/modules/managements/sc_tag/entities/tag.entity';
import { Category } from '@/modules/managements/sc_category/entities/category.entity';

@Injectable()
export class ProductService {
  constructor(
    @InjectRepository(Product)
    private readonly repo: Repository<Product>,
    @InjectRepository(Tag)
    private readonly tagRepo: Repository<Tag>,
    @InjectRepository(Category)
    private readonly categoryRepo: Repository<Category>,
    private readonly activityLogsService: ActivityLogsService,
  ) {}

  async findAll(query: QueryProductDto) {
    const { page = 1, limit = 20, search, searchField, sortBy, sortOrder } = query;
    const qb = this.repo.createQueryBuilder('product');

    qb
      .leftJoinAndSelect('product.category', 'category')
      .leftJoinAndSelect('product.tags', 'tags');

    if (search && searchField) {
      const allowed = QueryProductDto.searchableFields;
      if (allowed.includes(searchField)) {
        qb.where(`product.${searchField} LIKE :search`, { search: `%${search}%` });
      }
    } else if (search) {
      const conditions = QueryProductDto.searchableFields.map(
        (f) => `product.${f} LIKE :search`,
      );
      qb.where(`(${conditions.join(' OR ')})`, { search: `%${search}%` });
    }

    const sortable = QueryProductDto.sortableFields;
    const field = sortBy && sortable.includes(sortBy) ? `product.${sortBy}` : 'product.id';
    const order = sortOrder === 'ASC' ? 'ASC' : 'DESC';

    const [items, total] = await qb
      .skip((page - 1) * limit)
      .take(limit)
      .orderBy(field, order)
      .getManyAndCount();

    return {
      data: items,
      total,
      page,
      limit,
      totalPages: Math.ceil(total / limit),
    };
  }

  async findOne(id: number) {
    const mod = await this.repo.findOne({ where: { id }, relations: { category: true, tags: true } });
    if (!mod) throw new NotFoundException('Product not found');
    return mod;
  }

  async create(dto: CreateProductDto, req?: any) {
    const mod = this.repo.create({
      title: dto.title,
      description: dto.description,
      price: dto.price,
      stock: dto.stock,
      category_id: dto.category,
      tags: null,
      is_active: dto.is_active,
    } as any);
    const saved = await this.repo.save(mod) as unknown as Product;

    if (dto.tags && dto.tags.length > 0) {
      const tagsEntities = await this.tagRepo.findBy({ id: In(dto.tags) });
      saved.tags = tagsEntities;
      await this.repo.save(saved);
    }

    await this.activityLogsService.log({
      userId: req?.user?.sub,
      action: 'CREATE',
      entity: 'Product',
      entityId: saved.id,
      description: `Created product ${saved.id}`,
      metadata: { id: saved.id },
      ipAddress: req?.ip,
      userAgent: req?.headers?.['user-agent'],
    });

    return saved;
  }

  async update(id: number, dto: UpdateProductDto, req?: any) {
    const mod = await this.repo.findOne({ where: { id } });
    if (!mod) throw new NotFoundException('Product not found');

    if (dto.title !== undefined) mod.title = dto.title;
    if (dto.description !== undefined) mod.description = dto.description;
    if (dto.price !== undefined) mod.price = dto.price;
    if (dto.stock !== undefined) mod.stock = dto.stock;
    if (dto.category !== undefined) mod.category_id = dto.category;
    if (dto.tags !== undefined) { const entities = await this.tagRepo.findBy({ id: In(dto.tags) }); mod.tags = entities; }
    if (dto.is_active !== undefined) mod.is_active = dto.is_active;

    const saved = await this.repo.save(mod);

    await this.activityLogsService.log({
      userId: req?.user?.sub,
      action: 'UPDATE',
      entity: 'Product',
      entityId: saved.id,
      description: `Updated product ${saved.id}`,
      metadata: { id: saved.id },
      ipAddress: req?.ip,
      userAgent: req?.headers?.['user-agent'],
    });

    return saved;
  }

  async remove(id: number, req?: any) {
    const mod = await this.repo.findOne({ where: { id } });
    if (!mod) throw new NotFoundException('Product not found');

    await this.repo.remove(mod);

    await this.activityLogsService.log({
      userId: req?.user?.sub,
      action: 'DELETE',
      entity: 'Product',
      entityId: id,
      description: `Deleted product ${id}`,
      metadata: { id },
      ipAddress: req?.ip,
      userAgent: req?.headers?.['user-agent'],
    });
  }
}
