"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
var __param = (this && this.__param) || function (paramIndex, decorator) {
    return function (target, key) { decorator(target, key, paramIndex); }
};
var _a, _b, _c, _d;
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProductService = void 0;
// Auto-generated by System Creators — do not edit manually
const common_1 = require("@nestjs/common");
const typeorm_1 = require("@nestjs/typeorm");
const typeorm_2 = require("typeorm");
const product_entity_1 = require("../entities/product.entity");
const query_product_dto_1 = require("../dto/query-product.dto");
const activity_logs_service_1 = require("@/modules/activity-logs/services/activity-logs.service");
const tag_entity_1 = require("@/modules/managements/sc_tag/entities/tag.entity");
const category_entity_1 = require("@/modules/managements/sc_category/entities/category.entity");
let ProductService = class ProductService {
    repo;
    tagRepo;
    categoryRepo;
    activityLogsService;
    constructor(repo, tagRepo, categoryRepo, activityLogsService) {
        this.repo = repo;
        this.tagRepo = tagRepo;
        this.categoryRepo = categoryRepo;
        this.activityLogsService = activityLogsService;
    }
    async findAll(query) {
        const { page = 1, limit = 20, search, searchField, sortBy, sortOrder } = query;
        const qb = this.repo.createQueryBuilder('product');
        qb
            .leftJoinAndSelect('product.category', 'category')
            .leftJoinAndSelect('product.tags', 'tags');
        if (search && searchField) {
            const allowed = query_product_dto_1.QueryProductDto.searchableFields;
            if (allowed.includes(searchField)) {
                qb.where(`product.${searchField} LIKE :search`, { search: `%${search}%` });
            }
        }
        else if (search) {
            const conditions = query_product_dto_1.QueryProductDto.searchableFields.map((f) => `product.${f} LIKE :search`);
            qb.where(`(${conditions.join(' OR ')})`, { search: `%${search}%` });
        }
        const sortable = query_product_dto_1.QueryProductDto.sortableFields;
        const field = sortBy && sortable.includes(sortBy) ? `product.${sortBy}` : 'product.id';
        const order = sortOrder === 'ASC' ? 'ASC' : 'DESC';
        const [items, total] = await qb
            .skip((page - 1) * limit)
            .take(limit)
            .orderBy(field, order)
            .getManyAndCount();
        return {
            data: items,
            total,
            page,
            limit,
            totalPages: Math.ceil(total / limit),
        };
    }
    async findOne(id) {
        const mod = await this.repo.findOne({ where: { id }, relations: { category: true, tags: true } });
        if (!mod)
            throw new common_1.NotFoundException('Product not found');
        return mod;
    }
    async create(dto, req) {
        const mod = this.repo.create({
            title: dto.title,
            description: dto.description,
            price: dto.price,
            stock: dto.stock,
            category_id: dto.category,
            tags: null,
            is_active: dto.is_active,
        });
        const saved = await this.repo.save(mod);
        if (dto.tags && dto.tags.length > 0) {
            const tagsEntities = await this.tagRepo.findBy({ id: (0, typeorm_2.In)(dto.tags) });
            saved.tags = tagsEntities;
            await this.repo.save(saved);
        }
        await this.activityLogsService.log({
            userId: req?.user?.sub,
            action: 'CREATE',
            entity: 'Product',
            entityId: saved.id,
            description: `Created product ${saved.id}`,
            metadata: { id: saved.id },
            ipAddress: req?.ip,
            userAgent: req?.headers?.['user-agent'],
        });
        return saved;
    }
    async update(id, dto, req) {
        const mod = await this.repo.findOne({ where: { id } });
        if (!mod)
            throw new common_1.NotFoundException('Product not found');
        if (dto.title !== undefined)
            mod.title = dto.title;
        if (dto.description !== undefined)
            mod.description = dto.description;
        if (dto.price !== undefined)
            mod.price = dto.price;
        if (dto.stock !== undefined)
            mod.stock = dto.stock;
        if (dto.category !== undefined)
            mod.category_id = dto.category;
        if (dto.tags !== undefined) {
            const entities = await this.tagRepo.findBy({ id: (0, typeorm_2.In)(dto.tags) });
            mod.tags = entities;
        }
        if (dto.is_active !== undefined)
            mod.is_active = dto.is_active;
        const saved = await this.repo.save(mod);
        await this.activityLogsService.log({
            userId: req?.user?.sub,
            action: 'UPDATE',
            entity: 'Product',
            entityId: saved.id,
            description: `Updated product ${saved.id}`,
            metadata: { id: saved.id },
            ipAddress: req?.ip,
            userAgent: req?.headers?.['user-agent'],
        });
        return saved;
    }
    async remove(id, req) {
        const mod = await this.repo.findOne({ where: { id } });
        if (!mod)
            throw new common_1.NotFoundException('Product not found');
        await this.repo.remove(mod);
        await this.activityLogsService.log({
            userId: req?.user?.sub,
            action: 'DELETE',
            entity: 'Product',
            entityId: id,
            description: `Deleted product ${id}`,
            metadata: { id },
            ipAddress: req?.ip,
            userAgent: req?.headers?.['user-agent'],
        });
    }
};
exports.ProductService = ProductService;
exports.ProductService = ProductService = __decorate([
    (0, common_1.Injectable)(),
    __param(0, (0, typeorm_1.InjectRepository)(product_entity_1.Product)),
    __param(1, (0, typeorm_1.InjectRepository)(tag_entity_1.Tag)),
    __param(2, (0, typeorm_1.InjectRepository)(category_entity_1.Category)),
    __metadata("design:paramtypes", [typeof (_a = typeof typeorm_2.Repository !== "undefined" && typeorm_2.Repository) === "function" ? _a : Object, typeof (_b = typeof typeorm_2.Repository !== "undefined" && typeorm_2.Repository) === "function" ? _b : Object, typeof (_c = typeof typeorm_2.Repository !== "undefined" && typeorm_2.Repository) === "function" ? _c : Object, typeof (_d = typeof activity_logs_service_1.ActivityLogsService !== "undefined" && activity_logs_service_1.ActivityLogsService) === "function" ? _d : Object])
], ProductService);
