// Auto-generated by System Creators — do not edit manually
import { Controller, Get, Post, Put, Delete, Body, Param, Query, Request, ParseIntPipe } from '@nestjs/common';
import { CategoryService } from '../services/category.service';
import { CreateCategoryDto } from '../dto/create-category.dto';
import { UpdateCategoryDto } from '../dto/update-category.dto';
import { QueryCategoryDto } from '../dto/query-category.dto';
import { Permissions } from '@/common/decorators/permissions.decorator';
import { Roles } from '@/common/decorators/roles.decorator';

@Controller('generated/category')
export class CategoryController {
  constructor(private readonly service: CategoryService) {}

  @Get()
  @Permissions('Category Management', 'Full Access')
  @Roles('Admin', 'Super Admin')
  findAll(@Query() query: QueryCategoryDto) {
    return this.service.findAll(query);
  }

  @Get(':id')
  @Permissions('Category Management', 'Full Access')
  @Roles('Admin', 'Super Admin')
  findOne(@Param('id', ParseIntPipe) id: number) {
    return this.service.findOne(id);
  }

  @Post()
  @Permissions('Category Management', 'Full Access')
  @Roles('Admin', 'Super Admin')
  create(@Body() dto: CreateCategoryDto, @Request() req) {
    return this.service.create(dto, req);
  }

  @Put(':id')
  @Permissions('Category Management', 'Full Access')
  @Roles('Admin', 'Super Admin')
  update(@Param('id', ParseIntPipe) id: number, @Body() dto: UpdateCategoryDto, @Request() req) {
    return this.service.update(id, dto, req);
  }

  @Delete(':id')
  @Permissions('Category Management', 'Full Access')
  @Roles('Admin', 'Super Admin')
  remove(@Param('id', ParseIntPipe) id: number, @Request() req) {
    return this.service.remove(id, req);
  }
}
