// Auto-generated by System Creators — do not edit manually
import { Injectable, ConflictException, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Category } from '../entities/category.entity';
import { CreateCategoryDto } from '../dto/create-category.dto';
import { UpdateCategoryDto } from '../dto/update-category.dto';
import { QueryCategoryDto } from '../dto/query-category.dto';
import { ActivityLogsService } from '@/modules/activity-logs/services/activity-logs.service';

@Injectable()
export class CategoryService {
  constructor(
    @InjectRepository(Category)
    private readonly repo: Repository<Category>,
    private readonly activityLogsService: ActivityLogsService,
  ) {}

  async findAll(query: QueryCategoryDto) {
    const { page = 1, limit = 20, search, searchField, sortBy, sortOrder } = query;
    const qb = this.repo.createQueryBuilder('category');

    

    if (search && searchField) {
      const allowed = QueryCategoryDto.searchableFields;
      if (allowed.includes(searchField)) {
        qb.where(`category.${searchField} LIKE :search`, { search: `%${search}%` });
      }
    } else if (search) {
      const conditions = QueryCategoryDto.searchableFields.map(
        (f) => `category.${f} LIKE :search`,
      );
      qb.where(`(${conditions.join(' OR ')})`, { search: `%${search}%` });
    }

    const sortable = QueryCategoryDto.sortableFields;
    const field = sortBy && sortable.includes(sortBy) ? `category.${sortBy}` : 'category.id';
    const order = sortOrder === 'ASC' ? 'ASC' : 'DESC';

    const [items, total] = await qb
      .skip((page - 1) * limit)
      .take(limit)
      .orderBy(field, order)
      .getManyAndCount();

    return {
      data: items,
      total,
      page,
      limit,
      totalPages: Math.ceil(total / limit),
    };
  }

  async findOne(id: number) {
    const mod = await this.repo.findOne({ where: { id } });
    if (!mod) throw new NotFoundException('Category not found');
    return mod;
  }

  async create(dto: CreateCategoryDto, req?: any) {
    const mod = this.repo.create({
      name: dto.name,
      description: dto.description,
    });
    const saved = await this.repo.save(mod);

    await this.activityLogsService.log({
      userId: req?.user?.sub,
      action: 'CREATE',
      entity: 'Category',
      entityId: saved.id,
      description: `Created category ${saved.id}`,
      metadata: { id: saved.id },
      ipAddress: req?.ip,
      userAgent: req?.headers?.['user-agent'],
    });

    return saved;
  }

  async update(id: number, dto: UpdateCategoryDto, req?: any) {
    const mod = await this.repo.findOne({ where: { id } });
    if (!mod) throw new NotFoundException('Category not found');

    if (dto.name) mod.name = dto.name;
    if (dto.description) mod.description = dto.description;

    const saved = await this.repo.save(mod);

    await this.activityLogsService.log({
      userId: req?.user?.sub,
      action: 'UPDATE',
      entity: 'Category',
      entityId: saved.id,
      description: `Updated category ${saved.id}`,
      metadata: { id: saved.id },
      ipAddress: req?.ip,
      userAgent: req?.headers?.['user-agent'],
    });

    return saved;
  }

  async remove(id: number, req?: any) {
    const mod = await this.repo.findOne({ where: { id } });
    if (!mod) throw new NotFoundException('Category not found');

    await this.repo.remove(mod);

    await this.activityLogsService.log({
      userId: req?.user?.sub,
      action: 'DELETE',
      entity: 'Category',
      entityId: id,
      description: `Deleted category ${id}`,
      metadata: { id },
      ipAddress: req?.ip,
      userAgent: req?.headers?.['user-agent'],
    });
  }
}
