// Auto-generated by System Creators — do not edit manually
import { Injectable, ConflictException, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository, In } from 'typeorm';
import { Test2 } from '../entities/test2.entity';
import { CreateTest2Dto } from '../dto/create-test2.dto';
import { UpdateTest2Dto } from '../dto/update-test2.dto';
import { QueryTest2Dto } from '../dto/query-test2.dto';
import { ActivityLogsService } from '@/modules/activity-logs/services/activity-logs.service';

import { Category } from '@/modules/managements/sc_category/entities/category.entity';

@Injectable()
export class Test2Service {
  constructor(
    @InjectRepository(Test2)
    private readonly repo: Repository<Test2>,
    @InjectRepository(Category)
    private readonly categoryRepo: Repository<Category>,
    private readonly activityLogsService: ActivityLogsService,
  ) {}

  async findAll(query: QueryTest2Dto) {
    const { page = 1, limit = 20, search, searchField, sortBy, sortOrder } = query;
    const qb = this.repo.createQueryBuilder('test2');

    qb
      .leftJoinAndSelect('test2.test2', 'rel_test2');

    if (search && searchField) {
      const allowed = QueryTest2Dto.searchableFields;
      if (allowed.includes(searchField)) {
        qb.where(`test2.${searchField} LIKE :search`, { search: `%${search}%` });
      }
    } else if (search) {
      const conditions = QueryTest2Dto.searchableFields.map(
        (f) => `test2.${f} LIKE :search`,
      );
      qb.where(`(${conditions.join(' OR ')})`, { search: `%${search}%` });
    }

    const sortable = QueryTest2Dto.sortableFields;
    const field = sortBy && sortable.includes(sortBy) ? `test2.${sortBy}` : 'test2.id';
    const order = sortOrder === 'ASC' ? 'ASC' : 'DESC';

    const [items, total] = await qb
      .skip((page - 1) * limit)
      .take(limit)
      .orderBy(field, order)
      .getManyAndCount();

    return {
      data: items,
      total,
      page,
      limit,
      totalPages: Math.ceil(total / limit),
    };
  }

  async findOne(id: number) {
    const mod = await this.repo.findOne({ where: { id }, relations: { test2: true } });
    if (!mod) throw new NotFoundException('Test2 not found');
    return mod;
  }

  async create(dto: CreateTest2Dto, req?: any) {
    const mod = this.repo.create({
      test1: dto.test1,
      test2_id: dto.test2,
    } as any);
    const saved = await this.repo.save(mod) as unknown as Test2;



    await this.activityLogsService.log({
      userId: req?.user?.sub,
      action: 'CREATE',
      entity: 'Test2',
      entityId: saved.id,
      description: `Created test2 ${saved.id}`,
      metadata: { id: saved.id },
      ipAddress: req?.ip,
      userAgent: req?.headers?.['user-agent'],
    });

    return saved;
  }

  async update(id: number, dto: UpdateTest2Dto, req?: any) {
    const mod = await this.repo.findOne({ where: { id } });
    if (!mod) throw new NotFoundException('Test2 not found');

    if (dto.test1 !== undefined) mod.test1 = dto.test1;
    if (dto.test2 !== undefined) mod.test2_id = dto.test2;

    const saved = await this.repo.save(mod);

    await this.activityLogsService.log({
      userId: req?.user?.sub,
      action: 'UPDATE',
      entity: 'Test2',
      entityId: saved.id,
      description: `Updated test2 ${saved.id}`,
      metadata: { id: saved.id },
      ipAddress: req?.ip,
      userAgent: req?.headers?.['user-agent'],
    });

    return saved;
  }

  async remove(id: number, req?: any) {
    const mod = await this.repo.findOne({ where: { id } });
    if (!mod) throw new NotFoundException('Test2 not found');

    await this.repo.remove(mod);

    await this.activityLogsService.log({
      userId: req?.user?.sub,
      action: 'DELETE',
      entity: 'Test2',
      entityId: id,
      description: `Deleted test2 ${id}`,
      metadata: { id },
      ipAddress: req?.ip,
      userAgent: req?.headers?.['user-agent'],
    });
  }
}
