"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
var __param = (this && this.__param) || function (paramIndex, decorator) {
    return function (target, key) { decorator(target, key, paramIndex); }
};
var _a, _b, _c;
Object.defineProperty(exports, "__esModule", { value: true });
exports.Test2Service = void 0;
// Auto-generated by System Creators — do not edit manually
const common_1 = require("@nestjs/common");
const typeorm_1 = require("@nestjs/typeorm");
const typeorm_2 = require("typeorm");
const test2_entity_1 = require("../entities/test2.entity");
const query_test2_dto_1 = require("../dto/query-test2.dto");
const activity_logs_service_1 = require("../../../activity-logs/services/activity-logs.service");
const category_entity_1 = require("../../sc_category/entities/category.entity");
let Test2Service = class Test2Service {
    repo;
    categoryRepo;
    activityLogsService;
    constructor(repo, categoryRepo, activityLogsService) {
        this.repo = repo;
        this.categoryRepo = categoryRepo;
        this.activityLogsService = activityLogsService;
    }
    async findAll(query) {
        const { page = 1, limit = 20, search, searchField, sortBy, sortOrder } = query;
        const qb = this.repo.createQueryBuilder('test2');
        qb
            .leftJoinAndSelect('test2.test2', 'test2');
        if (search && searchField) {
            const allowed = query_test2_dto_1.QueryTest2Dto.searchableFields;
            if (allowed.includes(searchField)) {
                qb.where(`test2.${searchField} LIKE :search`, { search: `%${search}%` });
            }
        }
        else if (search) {
            const conditions = query_test2_dto_1.QueryTest2Dto.searchableFields.map((f) => `test2.${f} LIKE :search`);
            qb.where(`(${conditions.join(' OR ')})`, { search: `%${search}%` });
        }
        const sortable = query_test2_dto_1.QueryTest2Dto.sortableFields;
        const field = sortBy && sortable.includes(sortBy) ? `test2.${sortBy}` : 'test2.id';
        const order = sortOrder === 'ASC' ? 'ASC' : 'DESC';
        const [items, total] = await qb
            .skip((page - 1) * limit)
            .take(limit)
            .orderBy(field, order)
            .getManyAndCount();
        return {
            data: items,
            total,
            page,
            limit,
            totalPages: Math.ceil(total / limit),
        };
    }
    async findOne(id) {
        const mod = await this.repo.findOne({ where: { id }, relations: { test2: true } });
        if (!mod)
            throw new common_1.NotFoundException('Test2 not found');
        return mod;
    }
    async create(dto, req) {
        const mod = this.repo.create({
            test1: dto.test1,
            test2_id: dto.test2,
        });
        const saved = await this.repo.save(mod);
        await this.activityLogsService.log({
            userId: req?.user?.sub,
            action: 'CREATE',
            entity: 'Test2',
            entityId: saved.id,
            description: `Created test2 ${saved.id}`,
            metadata: { id: saved.id },
            ipAddress: req?.ip,
            userAgent: req?.headers?.['user-agent'],
        });
        return saved;
    }
    async update(id, dto, req) {
        const mod = await this.repo.findOne({ where: { id } });
        if (!mod)
            throw new common_1.NotFoundException('Test2 not found');
        if (dto.test1 !== undefined)
            mod.test1 = dto.test1;
        if (dto.test2 !== undefined)
            mod.test2_id = dto.test2;
        const saved = await this.repo.save(mod);
        await this.activityLogsService.log({
            userId: req?.user?.sub,
            action: 'UPDATE',
            entity: 'Test2',
            entityId: saved.id,
            description: `Updated test2 ${saved.id}`,
            metadata: { id: saved.id },
            ipAddress: req?.ip,
            userAgent: req?.headers?.['user-agent'],
        });
        return saved;
    }
    async remove(id, req) {
        const mod = await this.repo.findOne({ where: { id } });
        if (!mod)
            throw new common_1.NotFoundException('Test2 not found');
        await this.repo.remove(mod);
        await this.activityLogsService.log({
            userId: req?.user?.sub,
            action: 'DELETE',
            entity: 'Test2',
            entityId: id,
            description: `Deleted test2 ${id}`,
            metadata: { id },
            ipAddress: req?.ip,
            userAgent: req?.headers?.['user-agent'],
        });
    }
};
exports.Test2Service = Test2Service;
exports.Test2Service = Test2Service = __decorate([
    (0, common_1.Injectable)(),
    __param(0, (0, typeorm_1.InjectRepository)(test2_entity_1.Test2)),
    __param(1, (0, typeorm_1.InjectRepository)(category_entity_1.Category)),
    __metadata("design:paramtypes", [typeof (_a = typeof typeorm_2.Repository !== "undefined" && typeorm_2.Repository) === "function" ? _a : Object, typeof (_b = typeof typeorm_2.Repository !== "undefined" && typeorm_2.Repository) === "function" ? _b : Object, typeof (_c = typeof activity_logs_service_1.ActivityLogsService !== "undefined" && activity_logs_service_1.ActivityLogsService) === "function" ? _c : Object])
], Test2Service);
