// Auto-generated by System Creators — do not edit manually
import { QueryDto } from '@/common/dto/query.dto';

export class QueryTagDto extends QueryDto {
  static readonly sortableFields: string[] = ['id', 'name', 'createdAt', 'updatedAt'];
  static readonly searchableFields: string[] = ['name'];
}
