// Auto-generated by System Creators — do not edit manually
import { Injectable, ConflictException, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository, In } from 'typeorm';
import { Posts } from '../entities/posts.entity';
import { CreatePostsDto } from '../dto/create-posts.dto';
import { UpdatePostsDto } from '../dto/update-posts.dto';
import { QueryPostsDto } from '../dto/query-posts.dto';
import { ActivityLogsService } from '@/modules/activity-logs/services/activity-logs.service';

import { Tag } from '@/modules/managements/sc_tag/entities/tag.entity';
import { Category } from '@/modules/managements/sc_category/entities/category.entity';

@Injectable()
export class PostsService {
  constructor(
    @InjectRepository(Posts)
    private readonly repo: Repository<Posts>,
    @InjectRepository(Tag)
    private readonly tagRepo: Repository<Tag>,
    @InjectRepository(Category)
    private readonly categoryRepo: Repository<Category>,
    private readonly activityLogsService: ActivityLogsService,
  ) {}

  async findAll(query: QueryPostsDto) {
    const { page = 1, limit = 20, search, searchField, sortBy, sortOrder } = query;
    const qb = this.repo.createQueryBuilder('posts');

    qb
      .leftJoinAndSelect('posts.category', 'category')
      .leftJoinAndSelect('posts.tags', 'tags');

    if (search && searchField) {
      const allowed = QueryPostsDto.searchableFields;
      if (allowed.includes(searchField)) {
        qb.where(`posts.${searchField} LIKE :search`, { search: `%${search}%` });
      }
    } else if (search) {
      const conditions = QueryPostsDto.searchableFields.map(
        (f) => `posts.${f} LIKE :search`,
      );
      qb.where(`(${conditions.join(' OR ')})`, { search: `%${search}%` });
    }

    const sortable = QueryPostsDto.sortableFields;
    const field = sortBy && sortable.includes(sortBy) ? `posts.${sortBy}` : 'posts.id';
    const order = sortOrder === 'ASC' ? 'ASC' : 'DESC';

    const [items, total] = await qb
      .skip((page - 1) * limit)
      .take(limit)
      .orderBy(field, order)
      .getManyAndCount();

    return {
      data: items,
      total,
      page,
      limit,
      totalPages: Math.ceil(total / limit),
    };
  }

  async findOne(id: number) {
    const mod = await this.repo.findOne({ where: { id }, relations: { category: true, tags: true } });
    if (!mod) throw new NotFoundException('Posts not found');
    return mod;
  }

  async create(dto: CreatePostsDto, req?: any) {
    const mod = this.repo.create({
      title: dto.title,
      content: dto.content,
      category_id: dto.category,
      tags: null,
    } as any);
    const saved = await this.repo.save(mod) as unknown as Posts;

    if (dto.tags && dto.tags.length > 0) {
      const tagsEntities = await this.tagRepo.findBy({ id: In(dto.tags) });
      saved.tags = tagsEntities;
      await this.repo.save(saved);
    }

    await this.activityLogsService.log({
      userId: req?.user?.sub,
      action: 'CREATE',
      entity: 'Posts',
      entityId: saved.id,
      description: `Created posts ${saved.id}`,
      metadata: { id: saved.id },
      ipAddress: req?.ip,
      userAgent: req?.headers?.['user-agent'],
    });

    return saved;
  }

  async update(id: number, dto: UpdatePostsDto, req?: any) {
    const mod = await this.repo.findOne({ where: { id } });
    if (!mod) throw new NotFoundException('Posts not found');

    if (dto.title !== undefined) mod.title = dto.title;
    if (dto.content !== undefined) mod.content = dto.content;
    if (dto.category !== undefined) mod.category_id = dto.category;
    if (dto.tags !== undefined) { const entities = await this.tagRepo.findBy({ id: In(dto.tags) }); mod.tags = entities; }

    const saved = await this.repo.save(mod);

    await this.activityLogsService.log({
      userId: req?.user?.sub,
      action: 'UPDATE',
      entity: 'Posts',
      entityId: saved.id,
      description: `Updated posts ${saved.id}`,
      metadata: { id: saved.id },
      ipAddress: req?.ip,
      userAgent: req?.headers?.['user-agent'],
    });

    return saved;
  }

  async remove(id: number, req?: any) {
    const mod = await this.repo.findOne({ where: { id } });
    if (!mod) throw new NotFoundException('Posts not found');

    await this.repo.remove(mod);

    await this.activityLogsService.log({
      userId: req?.user?.sub,
      action: 'DELETE',
      entity: 'Posts',
      entityId: id,
      description: `Deleted posts ${id}`,
      metadata: { id },
      ipAddress: req?.ip,
      userAgent: req?.headers?.['user-agent'],
    });
  }
}
