// Auto-generated by System Creators — do not edit manually
import { Controller, Get, Post, Put, Delete, Body, Param, Query, Request, ParseIntPipe } from '@nestjs/common';
import { TagService } from '../services/tag.service';
import { CreateTagDto } from '../dto/create-tag.dto';
import { UpdateTagDto } from '../dto/update-tag.dto';
import { QueryTagDto } from '../dto/query-tag.dto';
import { Permissions } from '@/common/decorators/permissions.decorator';
import { Roles } from '@/common/decorators/roles.decorator';

@Controller('generated/tag')
export class TagController {
  constructor(private readonly service: TagService) {}

  @Get()
  @Permissions('Tag Management', 'Full Access')
  @Roles('Admin', 'Super Admin')
  findAll(@Query() query: QueryTagDto) {
    return this.service.findAll(query);
  }

  @Get(':id')
  @Permissions('Tag Management', 'Full Access')
  @Roles('Admin', 'Super Admin')
  findOne(@Param('id', ParseIntPipe) id: number) {
    return this.service.findOne(id);
  }

  @Post()
  @Permissions('Tag Management', 'Full Access')
  @Roles('Admin', 'Super Admin')
  create(@Body() dto: CreateTagDto, @Request() req) {
    return this.service.create(dto, req);
  }

  @Put(':id')
  @Permissions('Tag Management', 'Full Access')
  @Roles('Admin', 'Super Admin')
  update(@Param('id', ParseIntPipe) id: number, @Body() dto: UpdateTagDto, @Request() req) {
    return this.service.update(id, dto, req);
  }

  @Delete(':id')
  @Permissions('Tag Management', 'Full Access')
  @Roles('Admin', 'Super Admin')
  remove(@Param('id', ParseIntPipe) id: number, @Request() req) {
    return this.service.remove(id, req);
  }
}
