"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Test2Module = void 0;
// Auto-generated by System Creators — do not edit manually
const common_1 = require("@nestjs/common");
const typeorm_1 = require("@nestjs/typeorm");
const test2_entity_1 = require("./entities/test2.entity");
const test2_controller_1 = require("./controllers/test2.controller");
const test2_service_1 = require("./services/test2.service");
const activity_logs_module_1 = require("../../activity-logs/activity-logs.module");
const category_entity_1 = require("../sc_category/entities/category.entity");
let Test2Module = class Test2Module {
};
exports.Test2Module = Test2Module;
exports.Test2Module = Test2Module = __decorate([
    (0, common_1.Module)({
        imports: [typeorm_1.TypeOrmModule.forFeature([test2_entity_1.Test2, category_entity_1.Category]), activity_logs_module_1.ActivityLogsModule],
        controllers: [test2_controller_1.Test2Controller],
        providers: [test2_service_1.Test2Service],
        exports: [test2_service_1.Test2Service],
    })
], Test2Module);
