// Auto-generated by System Creators — do not edit manually
import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { Test2 } from './entities/test2.entity';
import { Test2Controller } from './controllers/test2.controller';
import { Test2Service } from './services/test2.service';
import { ActivityLogsModule } from '@/modules/activity-logs/activity-logs.module';
import { StorageModule } from '@/modules/storage/storage.module';

import { Category } from '@/modules/managements/sc_category/entities/category.entity';

@Module({
  imports: [TypeOrmModule.forFeature([Test2, Category]), ActivityLogsModule],
  controllers: [Test2Controller],
  providers: [Test2Service],
  exports: [Test2Service],
})
export class Test2Module {}
