// Auto-generated by System Creators — do not edit manually
import { Controller, Get, Post, Put, Delete, Body, Param, Query, Request, ParseIntPipe, UseInterceptors, UploadedFile } from '@nestjs/common';
import { FileInterceptor } from '@nestjs/platform-express';
import { memoryStorage } from 'multer';
import { StorageService } from '@/modules/storage/services/storage.service';
import { PostsService } from '../services/posts.service';
import { CreatePostsDto } from '../dto/create-posts.dto';
import { UpdatePostsDto } from '../dto/update-posts.dto';
import { QueryPostsDto } from '../dto/query-posts.dto';
import { Permissions } from '@/common/decorators/permissions.decorator';
import { Roles } from '@/common/decorators/roles.decorator';

@Controller('generated/posts')
export class PostsController {
  constructor(private readonly service: PostsService, private readonly storageService: StorageService) {}

  @Get()
  @Permissions('Post Management', 'Full Access')
  @Roles('Admin', 'Super Admin')
  findAll(@Query() query: QueryPostsDto) {
    return this.service.findAll(query);
  }

  @Get(':id')
  @Permissions('Post Management', 'Full Access')
  @Roles('Admin', 'Super Admin')
  findOne(@Param('id', ParseIntPipe) id: number) {
    return this.service.findOne(id);
  }

  @Post()
  @Permissions('Post Management', 'Full Access')
  @Roles('Admin', 'Super Admin')
  create(@Body() dto: CreatePostsDto, @Request() req) {
    return this.service.create(dto, req);
  }

  @Put(':id')
  @Permissions('Post Management', 'Full Access')
  @Roles('Admin', 'Super Admin')
  update(@Param('id', ParseIntPipe) id: number, @Body() dto: UpdatePostsDto, @Request() req) {
    return this.service.update(id, dto, req);
  }

  @Delete(':id')
  @Permissions('Post Management', 'Full Access')
  @Roles('Admin', 'Super Admin')
  remove(@Param('id', ParseIntPipe) id: number, @Request() req) {
    return this.service.remove(id, req);
  }
  @Post('upload')
  @Permissions('Post Management', 'Full Access')
  @Roles('Admin', 'Super Admin')
  @UseInterceptors(FileInterceptor('file', { storage: memoryStorage(), limits: { fileSize: 5 * 1024 * 1024 } }))
  uploadFile(@UploadedFile() file: Express.Multer.File) {
    const url = this.storageService.uploadFile(file, 'general');
    return { url };
  }
}
