"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.QueryProductDto = void 0;
// Auto-generated by System Creators — do not edit manually
const query_dto_1 = require("@/common/dto/query.dto");
class QueryProductDto extends query_dto_1.QueryDto {
    static sortableFields = ['id', 'title', 'price', 'stock', 'createdAt', 'updatedAt'];
    static searchableFields = ['title'];
}
exports.QueryProductDto = QueryProductDto;
