// Auto-generated by System Creators — do not edit manually
import { QueryDto } from '@/common/dto/query.dto';

export class QueryProductDto extends QueryDto {
  static readonly sortableFields: string[] = ['id', 'title', 'price', 'stock', 'createdAt', 'updatedAt'];
  static readonly searchableFields: string[] = ['title'];
}
