// Auto-generated by System Creators — do not edit manually
import { IsArray, IsNumber, IsOptional, IsString, MaxLength } from 'class-validator';

export class CreatePostsDto {
  @IsString()
  @MaxLength(255)
  title: string;

  @IsOptional()
  @IsString()
  thumbnail?: string;

  @IsOptional()
  @IsString()
  content?: string;

  @IsOptional()
  @IsOptional()
  @IsNumber()
  category?: number;

  @IsOptional()
  @IsOptional()
  @IsArray()
  tags?: number[];
}
