"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.QueryPostsDto = void 0;
// Auto-generated by System Creators — do not edit manually
const query_dto_1 = require("../../../../common/dto/query.dto");
class QueryPostsDto extends query_dto_1.QueryDto {
    static sortableFields = ['id', 'title', 'createdAt', 'updatedAt'];
    static searchableFields = ['title'];
}
exports.QueryPostsDto = QueryPostsDto;
