"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpdatePostsDto = void 0;
// Auto-generated by System Creators — do not edit manually
const mapped_types_1 = require("@nestjs/mapped-types");
const create_posts_dto_1 = require("./create-posts.dto");
class UpdatePostsDto extends (0, mapped_types_1.PartialType)(create_posts_dto_1.CreatePostsDto) {
}
exports.UpdatePostsDto = UpdatePostsDto;
