// Auto-generated by System Creators — do not edit manually
import { PartialType } from '@nestjs/mapped-types';
import { CreatePostsDto } from './create-posts.dto';

export class UpdatePostsDto extends PartialType(CreatePostsDto) {}
