// Auto-generated by System Creators — do not edit manually
import { Column, CreateDateColumn, Entity, JoinColumn, ManyToOne, PrimaryGeneratedColumn, UpdateDateColumn } from 'typeorm';

import { Category } from '@/modules/managements/sc_category/entities/category.entity';

@Entity('test2')
export class Test2 {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ type: 'varchar', length: 255, nullable: true })
  test1: string;

  @Column({ type: 'integer', nullable: true })
  test2_id: number;

  @ManyToOne(() => Category)
  @JoinColumn({ name: 'test2_id' })
  test2: Category;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}
