// Auto-generated by System Creators — do not edit manually
import { Controller, Get, Post, Put, Delete, Body, Param, Query, Request, ParseIntPipe } from '@nestjs/common';
import { Test2Service } from '../services/test2.service';
import { CreateTest2Dto } from '../dto/create-test2.dto';
import { UpdateTest2Dto } from '../dto/update-test2.dto';
import { QueryTest2Dto } from '../dto/query-test2.dto';
import { Permissions } from '@/common/decorators/permissions.decorator';
import { Roles } from '@/common/decorators/roles.decorator';

@Controller('generated/test2')
export class Test2Controller {
  constructor(private readonly service: Test2Service) {}

  @Get()
  @Permissions('T Management', 'Full Access')
  @Roles('Admin', 'Super Admin')
  findAll(@Query() query: QueryTest2Dto) {
    return this.service.findAll(query);
  }

  @Get(':id')
  @Permissions('T Management', 'Full Access')
  @Roles('Admin', 'Super Admin')
  findOne(@Param('id', ParseIntPipe) id: number) {
    return this.service.findOne(id);
  }

  @Post()
  @Permissions('T Management', 'Full Access')
  @Roles('Admin', 'Super Admin')
  create(@Body() dto: CreateTest2Dto, @Request() req) {
    return this.service.create(dto, req);
  }

  @Put(':id')
  @Permissions('T Management', 'Full Access')
  @Roles('Admin', 'Super Admin')
  update(@Param('id', ParseIntPipe) id: number, @Body() dto: UpdateTest2Dto, @Request() req) {
    return this.service.update(id, dto, req);
  }

  @Delete(':id')
  @Permissions('T Management', 'Full Access')
  @Roles('Admin', 'Super Admin')
  remove(@Param('id', ParseIntPipe) id: number, @Request() req) {
    return this.service.remove(id, req);
  }
}
