// Auto-generated by System Creators — do not edit manually
import { Controller, Get, Post, Put, Delete, Body, Param, Query, Request, ParseIntPipe, UseInterceptors, UploadedFile } from '@nestjs/common';
import { FileInterceptor } from '@nestjs/platform-express';
import { memoryStorage } from 'multer';
import { ProductService } from '../services/product.service';
import { CreateProductDto } from '../dto/create-product.dto';
import { UpdateProductDto } from '../dto/update-product.dto';
import { QueryProductDto } from '../dto/query-product.dto';
import { Permissions } from '@/common/decorators/permissions.decorator';
import { Roles } from '@/common/decorators/roles.decorator';

@Controller('generated/product')
export class ProductController {
  constructor(private readonly service: ProductService) {}

  @Get()
  @Permissions('Products Management', 'Full Access')
  @Roles('Admin', 'Super Admin')
  findAll(@Query() query: QueryProductDto) {
    return this.service.findAll(query);
  }

  @Get(':id')
  @Permissions('Products Management', 'Full Access')
  @Roles('Admin', 'Super Admin')
  findOne(@Param('id', ParseIntPipe) id: number) {
    return this.service.findOne(id);
  }

  @Post()
  @Permissions('Products Management', 'Full Access')
  @Roles('Admin', 'Super Admin')
  create(@Body() dto: CreateProductDto, @Request() req) {
    return this.service.create(dto, req);
  }

  @Put(':id')
  @Permissions('Products Management', 'Full Access')
  @Roles('Admin', 'Super Admin')
  update(@Param('id', ParseIntPipe) id: number, @Body() dto: UpdateProductDto, @Request() req) {
    return this.service.update(id, dto, req);
  }

  @Delete(':id')
  @Permissions('Products Management', 'Full Access')
  @Roles('Admin', 'Super Admin')
  remove(@Param('id', ParseIntPipe) id: number, @Request() req) {
    return this.service.remove(id, req);
  }
  @Post('upload')
  @Permissions('Products Management', 'Full Access')
  @Roles('Admin', 'Super Admin')
  @UseInterceptors(FileInterceptor('file', { storage: memoryStorage(), limits: { fileSize: 5 * 1024 * 1024 } }))
  uploadFile(@UploadedFile() file: Express.Multer.File) {
    // Save to server/storage/generated/product/
    // Return { url: '/api/storage/generated/product/' + file.originalname }
  }
}
