"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
var __param = (this && this.__param) || function (paramIndex, decorator) {
    return function (target, key) { decorator(target, key, paramIndex); }
};
var _a, _b;
Object.defineProperty(exports, "__esModule", { value: true });
exports.TagService = void 0;
// Auto-generated by System Creators — do not edit manually
const common_1 = require("@nestjs/common");
const typeorm_1 = require("@nestjs/typeorm");
const typeorm_2 = require("typeorm");
const tag_entity_1 = require("../entities/tag.entity");
const query_tag_dto_1 = require("../dto/query-tag.dto");
const activity_logs_service_1 = require("@/modules/activity-logs/services/activity-logs.service");
let TagService = class TagService {
    repo;
    activityLogsService;
    constructor(repo, activityLogsService) {
        this.repo = repo;
        this.activityLogsService = activityLogsService;
    }
    async findAll(query) {
        const { page = 1, limit = 20, search, searchField, sortBy, sortOrder } = query;
        const qb = this.repo.createQueryBuilder('tag');
        if (search && searchField) {
            const allowed = query_tag_dto_1.QueryTagDto.searchableFields;
            if (allowed.includes(searchField)) {
                qb.where(`tag.${searchField} LIKE :search`, { search: `%${search}%` });
            }
        }
        else if (search) {
            const conditions = query_tag_dto_1.QueryTagDto.searchableFields.map((f) => `tag.${f} LIKE :search`);
            qb.where(`(${conditions.join(' OR ')})`, { search: `%${search}%` });
        }
        const sortable = query_tag_dto_1.QueryTagDto.sortableFields;
        const field = sortBy && sortable.includes(sortBy) ? `tag.${sortBy}` : 'tag.id';
        const order = sortOrder === 'ASC' ? 'ASC' : 'DESC';
        const [items, total] = await qb
            .skip((page - 1) * limit)
            .take(limit)
            .orderBy(field, order)
            .getManyAndCount();
        return {
            data: items,
            total,
            page,
            limit,
            totalPages: Math.ceil(total / limit),
        };
    }
    async findOne(id) {
        const mod = await this.repo.findOne({ where: { id } });
        if (!mod)
            throw new common_1.NotFoundException('Tag not found');
        return mod;
    }
    async create(dto, req) {
        const mod = this.repo.create({
            name: dto.name,
            color: dto.color,
        });
        const saved = await this.repo.save(mod);
        await this.activityLogsService.log({
            userId: req?.user?.sub,
            action: 'CREATE',
            entity: 'Tag',
            entityId: saved.id,
            description: `Created tag ${saved.id}`,
            metadata: { id: saved.id },
            ipAddress: req?.ip,
            userAgent: req?.headers?.['user-agent'],
        });
        return saved;
    }
    async update(id, dto, req) {
        const mod = await this.repo.findOne({ where: { id } });
        if (!mod)
            throw new common_1.NotFoundException('Tag not found');
        if (dto.name)
            mod.name = dto.name;
        if (dto.color)
            mod.color = dto.color;
        const saved = await this.repo.save(mod);
        await this.activityLogsService.log({
            userId: req?.user?.sub,
            action: 'UPDATE',
            entity: 'Tag',
            entityId: saved.id,
            description: `Updated tag ${saved.id}`,
            metadata: { id: saved.id },
            ipAddress: req?.ip,
            userAgent: req?.headers?.['user-agent'],
        });
        return saved;
    }
    async remove(id, req) {
        const mod = await this.repo.findOne({ where: { id } });
        if (!mod)
            throw new common_1.NotFoundException('Tag not found');
        await this.repo.remove(mod);
        await this.activityLogsService.log({
            userId: req?.user?.sub,
            action: 'DELETE',
            entity: 'Tag',
            entityId: id,
            description: `Deleted tag ${id}`,
            metadata: { id },
            ipAddress: req?.ip,
            userAgent: req?.headers?.['user-agent'],
        });
    }
};
exports.TagService = TagService;
exports.TagService = TagService = __decorate([
    (0, common_1.Injectable)(),
    __param(0, (0, typeorm_1.InjectRepository)(tag_entity_1.Tag)),
    __metadata("design:paramtypes", [typeof (_a = typeof typeorm_2.Repository !== "undefined" && typeorm_2.Repository) === "function" ? _a : Object, typeof (_b = typeof activity_logs_service_1.ActivityLogsService !== "undefined" && activity_logs_service_1.ActivityLogsService) === "function" ? _b : Object])
], TagService);
