// Auto-generated by System Creators — do not edit manually
import { Injectable, ConflictException, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Tag } from '../entities/tag.entity';
import { CreateTagDto } from '../dto/create-tag.dto';
import { UpdateTagDto } from '../dto/update-tag.dto';
import { QueryTagDto } from '../dto/query-tag.dto';
import { ActivityLogsService } from '@/modules/activity-logs/services/activity-logs.service';

@Injectable()
export class TagService {
  constructor(
    @InjectRepository(Tag)
    private readonly repo: Repository<Tag>,
    private readonly activityLogsService: ActivityLogsService,
  ) {}

  async findAll(query: QueryTagDto) {
    const { page = 1, limit = 20, search, searchField, sortBy, sortOrder } = query;
    const qb = this.repo.createQueryBuilder('tag');

    

    if (search && searchField) {
      const allowed = QueryTagDto.searchableFields;
      if (allowed.includes(searchField)) {
        qb.where(`tag.${searchField} LIKE :search`, { search: `%${search}%` });
      }
    } else if (search) {
      const conditions = QueryTagDto.searchableFields.map(
        (f) => `tag.${f} LIKE :search`,
      );
      qb.where(`(${conditions.join(' OR ')})`, { search: `%${search}%` });
    }

    const sortable = QueryTagDto.sortableFields;
    const field = sortBy && sortable.includes(sortBy) ? `tag.${sortBy}` : 'tag.id';
    const order = sortOrder === 'ASC' ? 'ASC' : 'DESC';

    const [items, total] = await qb
      .skip((page - 1) * limit)
      .take(limit)
      .orderBy(field, order)
      .getManyAndCount();

    return {
      data: items,
      total,
      page,
      limit,
      totalPages: Math.ceil(total / limit),
    };
  }

  async findOne(id: number) {
    const mod = await this.repo.findOne({ where: { id } });
    if (!mod) throw new NotFoundException('Tag not found');
    return mod;
  }

  async create(dto: CreateTagDto, req?: any) {
    const mod = this.repo.create({
      name: dto.name,
      color: dto.color,
    });
    const saved = await this.repo.save(mod);

    await this.activityLogsService.log({
      userId: req?.user?.sub,
      action: 'CREATE',
      entity: 'Tag',
      entityId: saved.id,
      description: `Created tag ${saved.id}`,
      metadata: { id: saved.id },
      ipAddress: req?.ip,
      userAgent: req?.headers?.['user-agent'],
    });

    return saved;
  }

  async update(id: number, dto: UpdateTagDto, req?: any) {
    const mod = await this.repo.findOne({ where: { id } });
    if (!mod) throw new NotFoundException('Tag not found');

    if (dto.name) mod.name = dto.name;
    if (dto.color) mod.color = dto.color;

    const saved = await this.repo.save(mod);

    await this.activityLogsService.log({
      userId: req?.user?.sub,
      action: 'UPDATE',
      entity: 'Tag',
      entityId: saved.id,
      description: `Updated tag ${saved.id}`,
      metadata: { id: saved.id },
      ipAddress: req?.ip,
      userAgent: req?.headers?.['user-agent'],
    });

    return saved;
  }

  async remove(id: number, req?: any) {
    const mod = await this.repo.findOne({ where: { id } });
    if (!mod) throw new NotFoundException('Tag not found');

    await this.repo.remove(mod);

    await this.activityLogsService.log({
      userId: req?.user?.sub,
      action: 'DELETE',
      entity: 'Tag',
      entityId: id,
      description: `Deleted tag ${id}`,
      metadata: { id },
      ipAddress: req?.ip,
      userAgent: req?.headers?.['user-agent'],
    });
  }
}
